#!/usr/bin/env python3
"""为发布树生成官方风格的目录列表页（每个目录一个 index.html）。

对照基准：downloads.immortalwrt.org 的 dir-index.cgi 输出，规格如下
（开发期夹具见 sources/golden/，不入库）：

  <!DOCTYPE html>
  <html lang='en'>
  <head><meta charset='utf-8'/><link rel='stylesheet' href='/openwrt.css' />
  <title>Index of /path/</title></head>
  <body>
  <!-- This directory index page is auto-generated by dir-index.cgi -->
  <!-- Do not edit this file -->
  <div class='container'>
  <h1>Index of <a href="/"><em>(root)</em></a>/<a href="/a/">a</a>/</h1>
  <hr/>
  <table><tr><th class="n">File Name</th><th class="s">File Size</th><th class="d">Date</th></tr>
  <tr><td class="n"><a href="sub/">sub</a>/</td><td class="s">-</td><td class="d">Mon Sep  7 04:31:19 2026</td></tr>
  </table></div></body></html>

约定（均按官方实测）：
  * 体积一律 "1234.5 KB"（KB，一位小数），目录为 "-"
  * 日期为 ctime 风格，单位数日号用空格填充：`Mon Sep  7 04:31:19 2026`
  * 行序：目录在前、文件在后，各自按 C 区域排序
  * 目录项链接文本后带 "/"，其体积与 sha256sum 列均为 "-"
  * 含 profiles.json 的目录拆成 "Image Files" / "Supplementary Files" 两张表，
    镜像名以 profiles.json 中的 images[].name 为准，哈希取自同目录的 sha256sums
  * 不生成 "../" 行，也不把 index.html 自身列入

与官方的差异（有意为之）：
  * 若目录内存在 README.md，会在列表上方渲染一段说明块（中文），文件本身仍列入表格
  * 跳过站点自身资源（DEFAULT_SKIP_PATHS，如 assets/site/**）与隐藏项/构建目录
    （SKIP_NAMES）：它们不作为可下载内容出现，也不为其生成列表页
  * <head> 带站点图标与 theme-color（官方列表页没有；图标文件在站点根）

用法:
  ./generate-site-listings.py [--public-dir=public] [--dry-run] [--quiet]
"""

from __future__ import annotations

import argparse
import html
import json
import os
import re
import sys
import time
from pathlib import Path

from site_i18n import LANG_TOGGLE, SITE_JS_PATH, asset_url, icon_tags, line, title_tag

# 生成的列表页文件名
INDEX_NAME = "index.html"

# 官方的 KB 显示格式：字节/1024，保留一位小数
KB = 1024.0

# 生成列表页时要跳过的路径（相对 public 根的 POSIX 路径）。
# 站点自身的资源（字体/CSS/JS/搜索索引）属于站点 chrome：既不为它生成列表页，
# 也不在父目录的列表里出现——否则父目录会出现指向 404 的死链。
DEFAULT_SKIP_PATHS = ("assets/site",)

# 生成列表页时要跳过的名字（任何层级）：隐藏项与依赖/构建目录
SKIP_NAMES = {".git", "node_modules"}

# 站点配置文件（落地页声明；用于识别哪些目录属于落地页）
DEFAULT_SITE_CONFIG = "config/site.json"

# README 说明块的客户端渲染依赖（社区标准库，锁定版本 + SRI 校验；
# glue 脚本 public/assets/site/readme.js 负责取 README.md、套用 markdown-it、
# 再给代码块补行号与复制按钮）。哈希为实测值，改动版本必须同步更新。
README_CDN = {
    "markdown_it": "https://fastly.jsdelivr.net/npm/markdown-it@14.1.0/dist/markdown-it.min.js",
    "markdown_it_sri": "sha384-wLhprpjsmjc/XYIcF+LpMxd8yS1gss6jhevOp6F6zhiIoFK6AmHtm4bGKtehTani",
    "highlight_js": "https://fastly.jsdelivr.net/gh/highlightjs/cdn-release@11.11.1/build/highlight.min.js",
    "highlight_js_sri": "sha384-RH2xi4eIQ/gjtbs9fUXM68sLSi99C7ZWBRX1vDrVv6GQXRibxXLbwO2NGZB74MbU",
    "highlight_css": "https://fastly.jsdelivr.net/gh/highlightjs/cdn-release@11.11.1/build/styles/github.min.css",
    "highlight_css_sri": "sha384-eFTL69TLRZTkNfYZOLM+G04821K1qZao/4QLJbet1pP4tcF+fdXq/9CdqAbWRl/L",
}


def is_skipped(name: str, rel_dir: str, skip_paths: tuple[str, ...]) -> bool:
    """判断条目是否应跳过：隐藏项 / 构建目录 / 站点 chrome 子树。"""
    if name.startswith(".") or name in SKIP_NAMES:
        return True
    rel = f"{rel_dir}/{name}".strip("/")
    return any(rel == path or rel.startswith(path + "/") for path in skip_paths)


def fmt_size(size: int) -> str:
    """字节 → 官方风格体积字符串（KB，一位小数）。"""
    return f"{size / KB:.1f} KB"


def fmt_date(mtime: float) -> str:
    """时间戳 → ctime 风格字符串；单位数日号用空格填充（与官方一致）。"""
    lt = time.localtime(mtime)
    return f"{time.strftime('%a %b', lt)} {lt.tm_mday:2d} {time.strftime('%H:%M:%S %Y', lt)}"


def parse_sha256sums(path: Path) -> dict[str, str]:
    """解析 sha256sums（格式：`<hash> *<name>`），返回 文件名 → 哈希。"""
    hashes: dict[str, str] = {}
    if not path.is_file():
        return hashes
    try:
        content = path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return hashes
    for line in content.splitlines():
        match = re.match(r"^([0-9a-fA-F]{64})\s+\*?(.+)$", line.strip())
        if match:
            hashes[match.group(2)] = match.group(1).lower()
    return hashes


def image_names_from_profiles(path: Path) -> list[str]:
    """从 profiles.json 收集镜像文件名（官方镜像表的判定依据）。"""
    if not path.is_file():
        return []
    try:
        data = json.loads(path.read_text(encoding="utf-8", errors="replace"))
    except (OSError, json.JSONDecodeError):
        return []
    names: list[str] = []
    for profile in (data.get("profiles") or {}).values():
        for image in profile.get("images") or []:
            name = image.get("name")
            if name and name not in names:
                names.append(name)
    return names


def common_prefix(names: list[str]) -> str:
    """求一组文件名的公共前缀（官方用于说明“短名共享同一前缀”）。"""
    if not names:
        return ""
    prefix = names[0]
    for name in names[1:]:
        while prefix and not name.startswith(prefix):
            prefix = prefix[:-1]
    # 收窄到最后一个 '-' 之后，避免截断到半个字段
    cut = prefix.rfind("-")
    return prefix[: cut + 1] if cut >= 0 else ""


def _render_link(match: re.Match[str]) -> str:
    """行内链接：接受站内相对路径与 http(s)，其它协议原样保留（不做链接化）。"""
    text, href = match.group(1), match.group(2)
    if href.startswith(("https://", "http://", "/", "./", "../", "#")):
        return f'<a href="{href}">{text}</a>'
    return match.group(0)


def render_inline_markdown(text: str) -> str:
    """极简行内 Markdown：转义 → 代码 → 粗体/斜体 → 链接（含站内相对链接）。"""
    escaped = html.escape(text, quote=False)
    escaped = re.sub(r"`([^`]+)`", r"<code>\1</code>", escaped)
    escaped = re.sub(r"\*\*([^*]+)\*\*", r"<strong>\1</strong>", escaped)
    escaped = re.sub(r"(?<!\*)\*([^*]+)\*(?!\*)", r"<em>\1</em>", escaped)
    escaped = re.sub(r"\[([^\]]+)\]\(([^)\s]+)\)", _render_link, escaped)
    return escaped


_LANG_ALIASES = {"sh": "bash", "shell": "bash", "console": "bash", "bash": "bash",
                 "json": "json", "": "", "txt": "", "text": "", "pre": ""}

# 语言标记占位符用的字母表（避免与数字/单词正则冲突）
_PLACEHOLDER_LETTERS = "abcdefghijklmnopqrstuvwxyz"


def _stash(store: list[str], fragment: str) -> str:
    """把已生成的 HTML 片段暂存起来，返回占位符（防止后续正则改坏标记）。"""
    store.append(fragment)
    return f"\x00{_PLACEHOLDER_LETTERS[len(store) - 1]}\x00"


def _unstash(text: str, store: list[str]) -> str:
    """回填占位符。"""
    for idx, fragment in enumerate(store):
        text = text.replace(f"\x00{_PLACEHOLDER_LETTERS[idx]}\x00", fragment)
    return text


def _highlight_bash_line(line: str) -> str:
    """bash 行高亮：注释 / 字符串 / 变量 / 行首命令。"""
    escaped = html.escape(line, quote=False)
    store: list[str] = []

    comment = ""
    match = re.search(r"(^|\s)(#.*)$", escaped)
    if match:
        comment = match.group(2)
        escaped = escaped[: match.start(2)].rstrip()

    escaped = re.sub(r'("[^"]*"|\'[^\']*\')',
                     lambda m: _stash(store, f'<span class="s">{m.group(1)}</span>'), escaped)
    escaped = re.sub(r"(\$\{[^}]+\}|\$[A-Za-z_][A-Za-z0-9_]*)",
                     lambda m: _stash(store, f'<span class="v">{m.group(1)}</span>'), escaped)
    escaped = re.sub(r"^(\s*)((?:sudo\s+)?[A-Za-z0-9_./-]+)",
                     lambda m: m.group(1) + _stash(store, f'<span class="k">{m.group(2)}</span>'), escaped)

    result = _unstash(escaped, store)
    if comment:
        result = (result.rstrip() + " " if result.strip() else "") + f'<span class="c">{comment}</span>'
    return result


def _highlight_json_line(line: str) -> str:
    """JSON 行高亮：字符串 / 字面量 / 数字。"""
    escaped = html.escape(line, quote=False)
    store: list[str] = []
    escaped = re.sub(r'("(?:[^"\\]|\\.)*")',
                     lambda m: _stash(store, f'<span class="s">{m.group(1)}</span>'), escaped)
    escaped = re.sub(r"\b(true|false|null)\b",
                     lambda m: _stash(store, f'<span class="k">{m.group(1)}</span>'), escaped)
    escaped = re.sub(r"(?<![\w.])(-?\d+(?:\.\d+)?)(?![\w.])",
                     lambda m: _stash(store, f'<span class="n">{m.group(1)}</span>'), escaped)
    return _unstash(escaped, store)


def _render_code_block(code: str, lang: str) -> str:
    """代码块：逐行包裹（供 CSS 计数器出行号）+ 语言高亮 + 复制按钮。

    注意不要把标记与内容用换行分隔——那会在 <pre> 里多出一个空首行。
    """
    normalized = _LANG_ALIASES.get(lang, "")
    lines = code.split("\n")
    if normalized == "bash":
        highlighted = [_highlight_bash_line(line) for line in lines]
    elif normalized == "json":
        highlighted = [_highlight_json_line(line) for line in lines]
    else:
        highlighted = [html.escape(line, quote=False) for line in lines]

    # 行之间不能有真实换行：<pre> 的 white-space: pre 会把换行再渲染成一个空行，
    # 导致整块行距翻倍（.code-line 本身是 block，不需要换行分隔）
    body = "".join(f'<span class="code-line">{line}</span>' for line in highlighted)
    lang_attr = f' data-lang="{html.escape(lang, quote=True)}"' if lang else ""
    return (
        f'<div class="code-block"{lang_attr}>'
        '<button class="copy-btn" type="button" hidden>复制</button>'
        f'<pre class="code"><code>{body}</code></pre>'
        "</div>"
    )


def render_markdown(text: str) -> str:
    """极简块级 Markdown：标题 / 列表（含有序与嵌套）/ 代码块 / 分隔线 / 引用 / 段落。

    只支持 README 说明块用的子集，避免引入第三方依赖。
    """
    lines = text.splitlines()
    out: list[str] = []
    in_code = False
    code_lang = ""
    code_lines: list[str] = []
    list_stack: list[str] = []
    paragraph: list[str] = []

    def flush_paragraph() -> None:
        if paragraph:
            out.append(f"<p>{render_inline_markdown(' '.join(paragraph))}</p>")
            paragraph.clear()

    def close_lists(to_depth: int = 0) -> None:
        while len(list_stack) > to_depth:
            out.append(f"</{list_stack.pop()}>")

    for raw in lines:
        line = raw.rstrip()

        fence = re.match(r"^\s*```\s*([A-Za-z0-9_+-]*)\s*$", line)
        if fence:
            flush_paragraph()
            close_lists()
            if in_code:
                out.append(_render_code_block("\n".join(code_lines), code_lang))
                code_lines = []
                in_code = False
            else:
                in_code = True
                code_lang = fence.group(1).lower()
            continue
        if in_code:
            code_lines.append(raw)
            continue

        if not line.strip():
            flush_paragraph()
            close_lists()
            continue

        if re.match(r"^(?:-{3,}|\*{3,}|_{3,})\s*$", line):
            flush_paragraph()
            close_lists()
            out.append("<hr/>")
            continue

        heading = re.match(r"^(#{1,6})\s+(.*)$", line)
        if heading:
            flush_paragraph()
            close_lists()
            level = min(len(heading.group(1)) + 1, 6)  # 页面里已有 h1/h2
            out.append(f"<h{level}>{render_inline_markdown(heading.group(2))}</h{level}>")
            continue

        item = re.match(r"^(\s*)(?:[-*+]|\d+\.)\s+(.*)$", line)
        if item:
            flush_paragraph()
            tag = "ol" if re.match(r"^\s*\d+\.", line) else "ul"
            depth = min(len(item.group(1)) // 2 + 1, 3)
            close_lists(depth)
            if len(list_stack) == depth and list_stack[-1] != tag:
                out.append(f"</{list_stack.pop()}>")
            while len(list_stack) < depth:
                out.append(f"<{tag}>")
                list_stack.append(tag)
            out.append(f"<li>{render_inline_markdown(item.group(2))}</li>")
            continue

        quote = re.match(r"^>\s?(.*)$", line)
        if quote:
            flush_paragraph()
            close_lists()
            out.append(f"<blockquote>{render_inline_markdown(quote.group(1))}</blockquote>")
            continue
        paragraph.append(line.strip())
    flush_paragraph()
    close_lists()
    if in_code:
        out.append(_render_code_block("\n".join(code_lines), code_lang))
    return "\n".join(out)


def breadcrumb(rel_dir: str) -> str:
    """官方面包屑：Index of <a href="/"><em>(root)</em></a>/<a …>seg</a>/…

    (root) 也参与双语切换（显示为「(根目录)」/「(root)」）；各级目录名是路径，不翻译。
    """
    parts = [p for p in rel_dir.split("/") if p]
    crumbs = ['<a href="/">' + line("(根目录)", "(root)", "em") + "</a>"]
    walked: list[str] = []
    for part in parts:
        walked.append(part)
        crumbs.append(f'<a href="/{"/".join(walked)}/"> {html.escape(part)} </a>')
    return "\n/\n".join(crumbs)


def table_row(name: str, is_dir: bool, size: int, mtime: float, digest: str | None,
              display: str | None = None) -> str:
    """一行表格数据（官方 class 约定：n/s/d/sh）。"""
    label = display if display is not None else name
    href = html.escape(name + ("/" if is_dir else ""), quote=True)
    text = html.escape(label, quote=False) + ("/" if is_dir else "")
    size_cell = "-" if is_dir else fmt_size(size)
    hash_cell = "-" if (is_dir or not digest) else digest
    return (
        f'<tr><td class="n"><a href="{href}">{text}</a></td>'
        f'<td class="sh">{hash_cell}</td>'
        f'<td class="s">{size_cell}</td>'
        f'<td class="d">{fmt_date(mtime)}</td></tr>'
    )


def plain_row(name: str, is_dir: bool, size: int, mtime: float) -> str:
    """普通目录列表的行（无 sha256sum 列）。"""
    href = html.escape(name + ("/" if is_dir else ""), quote=True)
    text = html.escape(name, quote=False) + ("/" if is_dir else "")
    size_cell = "-" if is_dir else fmt_size(size)
    return (
        f'<tr><td class="n"><a href="{href}">{text}</a></td>'
        f'<td class="s">{size_cell}</td>'
        f'<td class="d">{fmt_date(mtime)}</td></tr>'
    )


def render_page(public_dir: Path, rel_dir: str, entries: list[dict], hashes: dict[str, str],
                image_names: list[str], readme_html: str | None, stylesheet: str = "") -> str:
    """渲染一个目录的 index.html（immortalwrt/dir-index.cgi 风格）。"""
    path_for_title = f"/{rel_dir}/" if rel_dir else "/"
    head = [
        "<!DOCTYPE html>",
        "<html lang='en'>",
        "<head>",
        "<meta charset='utf-8'/>",
        # 官方样式表来自配置（脚本里不写死任何发行版地址）；未配置就只用站点自身的
        *([f"<link rel='stylesheet' href='{stylesheet}' />"] if stylesheet else []),
        f"<link rel='stylesheet' href='{asset_url(public_dir, 'assets/site/base.css')}' />",
        icon_tags(public_dir),
        # README 说明块才需要 highlight.js 主题与站点样式（含 base64 内联字体）
        *([
            f"<link rel='stylesheet' href='{README_CDN['highlight_css']}' "
            f"integrity='{README_CDN['highlight_css_sri']}' crossorigin='anonymous' />",
            f"<link rel='stylesheet' href='{asset_url(public_dir, 'assets/site/site.css')}' />",
        ] if readme_html else []),
        title_tag(f"目录索引 {path_for_title}", f"Index of {path_for_title}"),
        "</head>",
        "",
        "<body>",
        "<!-- This directory index page is auto-generated by dir-index.cgi -->",
        "<!-- Do not edit this file -->",
        "<div class='container'>",
        LANG_TOGGLE,
        "<h1>",
        line("目录索引", "Index of"),
        breadcrumb(rel_dir),
        "</h1>",
        "<hr/>",
    ]

    body: list[str] = []
    if readme_html:
        # data-readme-src 指向同目录的 README.md（已随站点发布）：客户端脚本据此渲染；
        # 其中服务端渲染结果作为无 JS 时的兜底，渲染失败也不至于空块
        body.append('<div class="readme markdown-body" data-readme-src="./README.md">')
        body.append(readme_html)
        body.append("</div>")

    dirs = [e for e in entries if e["is_dir"]]
    files = [e for e in entries if not e["is_dir"]]

    if image_names:
        images_set = set(image_names)
        images = [f for f in files if f["name"] in images_set]
        supplement = [f for f in files if f["name"] not in images_set]
        prefix = common_prefix([f["name"] for f in images])
        target_label = rel_dir.split("targets/", 1)[-1] if "targets/" in rel_dir else rel_dir

        body.append(line("镜像文件", "Image Files", "h2"))
        prefix_note_zh = f"下方缩短的镜像文件名共享同一前缀：<code>{html.escape(prefix)}</code>" if prefix else ""
        prefix_note_en = (f" Shortened image file names below have the same prefix: "
                          f"<code>{html.escape(prefix)}</code>") if prefix else ""
        body.append(line(
            f"这些是 {html.escape(target_label)} 目标平台的镜像文件。请核对下载文件的 sha256sum "
            f"是否与下方一致。{prefix_note_zh}",
            f"These are the image files for the {html.escape(target_label)} target. Check that the "
            f"sha256sum of the file you downloaded matches the sha256sum below.{prefix_note_en}",
            "p",
            raw=True,
        ))
        body.append("<table>")
        body.append(
            "<tr>"
            + line("设备镜像", "Image for your Device", "th", attrs=' class="n"')
            + line("sha256sum", "sha256sum", "th")
            + line("文件大小", "File Size", "th", attrs=' class="s"')
            + line("日期", "Date", "th", attrs=' class="d"')
            + "</tr>"
        )
        for entry in sorted(images, key=lambda e: e["name"]):
            display = entry["name"][len(prefix):] if prefix and entry["name"].startswith(prefix) else entry["name"]
            body.append(table_row(entry["name"], False, entry["size"], entry["mtime"],
                                  hashes.get(entry["name"]), display))
        body.append("</table>")

        body.append(line("补充文件", "Supplementary Files", "h2"))
        body.append(line(
            f"这些是 {html.escape(target_label)} 目标平台的补充资源，包含构建工具、imagebuilder、"
            "sha256sum、GPG 签名文件及其它有用文件。",
            f"These are supplementary resources for the {html.escape(target_label)} target. They include "
            "build tools, the imagebuilder, sha256sum, GPG signature file, and other useful files.",
            "p",
        ))
        body.append("<table>")
        body.append(
            "<tr>"
            + line("文件名", "Filename", "th", attrs=' class="n"')
            + line("sha256sum", "sha256sum", "th")
            + line("文件大小", "File Size", "th", attrs=' class="s"')
            + line("日期", "Date", "th", attrs=' class="d"')
            + "</tr>"
        )
        for entry in sorted(dirs, key=lambda e: e["name"]) + sorted(supplement, key=lambda e: e["name"]):
            body.append(table_row(entry["name"], entry["is_dir"], entry["size"], entry["mtime"],
                                  hashes.get(entry["name"])))
        body.append("</table>")
    else:
        body.append("<table>")
        body.append(
            "<tr>"
            + line("文件名", "File Name", "th", attrs=' class="n"')
            + line("文件大小", "File Size", "th", attrs=' class="s"')
            + line("日期", "Date", "th", attrs=' class="d"')
            + "</tr>"
        )
        for entry in sorted(dirs, key=lambda e: e["name"]) + sorted(files, key=lambda e: e["name"]):
            body.append(plain_row(entry["name"], entry["is_dir"], entry["size"], entry["mtime"]))
        body.append("</table>")

    tail = [
        *([
            f"<script src='{README_CDN['markdown_it']}' "
            f"integrity='{README_CDN['markdown_it_sri']}' crossorigin='anonymous'></script>",
            f"<script src='{README_CDN['highlight_js']}' "
            f"integrity='{README_CDN['highlight_js_sri']}' crossorigin='anonymous'></script>",
            f"<script src='{asset_url(public_dir, 'assets/site/readme.js')}' defer></script>",
        ] if readme_html else []),
        f"<script src='{asset_url(public_dir, SITE_JS_PATH)}' defer></script>",
        "</div>",
        "</body>",
        "</html>",
        "",
    ]
    return "\n".join(head + body + tail)


def collect_entries(directory: Path, rel_dir: str, skip_paths: tuple[str, ...]) -> list[dict]:
    """列出一个目录的直接子项（跳过 index.html、隐藏项与站点 chrome）。"""
    entries: list[dict] = []
    for child in sorted(directory.iterdir(), key=lambda p: p.name):
        if child.name == INDEX_NAME or is_skipped(child.name, rel_dir, skip_paths):
            continue
        try:
            stat = child.stat()
        except OSError:
            continue
        entries.append({
            "name": child.name,
            "is_dir": child.is_dir(),
            "size": 0 if child.is_dir() else stat.st_size,
            "mtime": stat.st_mtime,
        })
    return entries


def generate_tree(public_dir: Path, dry_run: bool, quiet: bool,
                  skip_paths: tuple[str, ...], landing_paths: tuple[str, ...],
                  stylesheet: str = "") -> int:
    """递归生成整棵树的目录列表页，返回生成的页面数。

    skip_paths:    完全不处理的子树（站点 chrome 等）
    landing_paths: 落地页路径（站点根与各发行版根）——本脚本不写这些目录的
                   index.html，避免覆盖落地页生成器的产物（两脚本曾因此互相覆盖）
    stylesheet:    站点级样式表（来自 config/site.json；空表示只用站点自身的）
    """
    generated = 0
    for current, subdirs, _files in os.walk(public_dir):
        # 稳定遍历顺序，便于复现
        subdirs.sort()
        directory = Path(current)
        rel = directory.relative_to(public_dir).as_posix()
        rel = "" if rel == "." else rel

        # 跳过的子树既不生成页面，也不会出现在父目录的列表里
        subdirs[:] = [d for d in subdirs if not is_skipped(d, rel, skip_paths)]

        # 落地页目录交给 generate-site-landing.py，这里只统计、不写入
        if rel in landing_paths:
            if not quiet:
                print(f"  [跳过落地页] /{rel}/")
            continue

        entries = collect_entries(directory, rel, skip_paths)
        hashes = parse_sha256sums(directory / "sha256sums")
        image_names = image_names_from_profiles(directory / "profiles.json")

        readme_html = None
        readme = directory / "README.md"
        if readme.is_file():
            try:
                readme_html = render_markdown(readme.read_text(encoding="utf-8", errors="replace"))
            except OSError:
                readme_html = None

        page = render_page(public_dir, rel, entries, hashes, image_names, readme_html, stylesheet)
        target = directory / INDEX_NAME
        if not dry_run:
            target.write_text(page, encoding="utf-8")
        generated += 1
        if not quiet:
            print(f"  {'[dry-run] ' if dry_run else ''}/{rel}/  → {len(entries)} 项"
                  f"{' + README' if readme_html else ''}")
    return generated


def load_site_config(config_path: Path) -> dict:
    """读取站点配置；缺失或损坏时返回空表（列表页仍可生成，只是少站点级装饰）。"""
    if not config_path.is_file():
        return {}
    try:
        data = json.loads(config_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {}
    return data if isinstance(data, dict) else {}


def resolve_landing_paths(explicit: str, config: dict) -> tuple[str, ...]:
    """解析「落地页路径」：站点根 + site.json 里声明的发行版根。

    这些目录的 index.html 由 generate-site-landing.py 负责，本脚本不得写入，
    否则两个生成器的执行顺序会决定谁生效（曾出现列表页覆盖落地页）。
    """
    if explicit:
        return tuple(p.strip().strip("/") for p in explicit.split(",") if p.strip())

    paths: list[str] = [""]  # 站点根
    for firmware in config.get("firmwares", []):
        if isinstance(firmware, dict) and firmware.get("id"):
            paths.append(str(firmware["id"]))
    return tuple(paths)


def main() -> int:
    parser = argparse.ArgumentParser(
        description="为发布树生成官方风格的目录列表页（每个目录一个 index.html）",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("--public-dir", default="public", help="发布树根目录（默认 public）")
    parser.add_argument("--dry-run", action="store_true", help="只统计不写文件")
    parser.add_argument("--quiet", action="store_true", help="不打印每个目录")
    parser.add_argument("--skip", default=",".join(DEFAULT_SKIP_PATHS),
                        help="不生成列表页的路径（相对 public 根，逗号分隔；"
                             f"默认 {','.join(DEFAULT_SKIP_PATHS)}）")
    parser.add_argument("--config", default=DEFAULT_SITE_CONFIG,
                        help=f"站点配置（用于识别落地页路径，默认 {DEFAULT_SITE_CONFIG}）")
    parser.add_argument("--landing-paths", default="",
                        help="落地页路径（逗号分隔；缺省自动取 site.json 的发行版 id + 站点根）")
    args = parser.parse_args()

    public_dir = Path(args.public_dir).resolve()
    if not public_dir.is_dir():
        print(f"错误: 目录不存在: {public_dir}", file=sys.stderr)
        return 1

    skip_paths = tuple(p.strip().strip("/") for p in args.skip.split(",") if p.strip())
    config = load_site_config(Path(args.config))
    landing_paths = resolve_landing_paths(args.landing_paths, config)
    stylesheet = str(config.get("stylesheet") or "")

    print(f"生成目录列表页: {public_dir}{'（dry-run）' if args.dry_run else ''}"
          f"（跳过: {', '.join(skip_paths) if skip_paths else '无'}"
          f"；落地页目录: {', '.join('/' + p + '/' for p in landing_paths)}）")
    count = generate_tree(public_dir, args.dry_run, args.quiet, skip_paths, landing_paths, stylesheet)
    print(f"完成: 共 {count} 个目录{'（未写入）' if args.dry_run else ''}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
